config/routes.rb
Modlr::Application.routes.draw do
  
  get "users/show"
  
  resources :pins

  resources :casts

  devise_for :users

  get "users/:id" => "users#show", as: :user

  get "casts/:id" => "home#index" 

  root "pages#home"

  get "about" => "pages#about"

  get "contact" => "pages#contact"

  

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	
	validates :name, presence: true
	validates :user_name, presence: true
	validates :age, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :bio, presence: true

	mount_uploader :image, ImageUploader
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:name, :user_name, :age, :city, :state, :bio, :credits, :image, :remote_image_url)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_for(@pin) do |f| %>
        <% if @pin.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

            <ul>
            <% @pin.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :image %><br>
          <%= f.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :remote_image_url, "or image url" %><br>
          <%= f.file_field :remote_image_url, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :user_name %><br>
          <%= f.text_field :user_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :age %><br>
          <%= f.text_field :age, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :state %><br>
          <%= f.text_field :state, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :bio %><br>
          <%= f.text_area :bio, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :credits %><br>
          <%= f.text_area :credits, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "Create Profile", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pins/_pin.html.erb
<div class="box panel panel-default">
    <%= image_tag pin.image_url, class: "image-responsive" %>

    <p><%= pin.user_name %></p>

    <p><%= pin.city %>, <%= pin.state %></p>

    <!--<h2><%= pin.name %></h2>-->

    <!--<h3>Age:</h3>
    <%= pin.age %>-->

    <!--<h3>Bio:</h3>
    <%= pin.bio %>

    <h3>Credits:</h3>
    <%= pin.credits %>-->
  <%= link_to 'Show', pin %>
  <% if pin.user == current_user %>
    <%= link_to 'Edit', edit_pin_path(pin) %>
    <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/pins/edit.html.erb
<div class="container">
	<h1>Editing pic</h1>
</div>

<%= render 'form' %>

<div class="container">
	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', user_path(current_user) %>
</div>

app/views/pins/index.html.erb
<div class="container">
  <h1>All models index</h1>
  <% if user_signed_in? %>
    <%= link_to 'Add a new photo', new_pin_path, class: "space btn btn-primary btn-lg" %>
  <% end %>
  <div id="pins" class="transitions-enabled">
    <%= render @pins %>
  </div>
</div>

app/views/pins/new.html.erb
<div class="container">

	<h1>New pin</h1>

	<%= render 'form' %>

	<%= link_to 'Back', user_path(current_user) %>
	
</div>

app/views/pins/show.html.erb
<div class="container">
  <h2>Show</h2>
  
  <div class="row">
    <div class="col-md-4 center">
      <%= image_tag @pin.image_url(:thumb) %>
      <h1><strong><%= @pin.name %></strong></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <p>
        <strong>User name:</strong>
        <%= @pin.user_name %>
      </p>
        <hr>
      <p>
        <strong>User id:</strong>
        <%= @pin.user.email %>
      </p>
      <hr>
      <p>
        <strong>Age:</strong>
        <%= @pin.age %>
      </p>
      <hr>
      <p>
        <strong>City:</strong>
        <%= @pin.city %>
      </p>
      <hr>
      <p>
        <strong>State:</strong>
        <%= @pin.state %>
      </p>
      <hr>
      <p>
        <strong>Bio:</strong>
        <%= @pin.bio %>
      </p>
      <hr>
      <p>
        <strong>Credits:</strong>
        <%= @pin.credits %>
      </p>

      <hr class="heavy">

      
      <% if @pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(@pin) %> |
      <% end %>
    
      <%= link_to 'Back', pins_path %>
    </div>
    </div>
  </div>
</div>