config/routes.rb
Modlr::Application.routes.draw do
  
  get "users/show"
  
  resources :pins

  resources :casts

  devise_for :users

  get "users/:id" => "users#show", as: :user

  get "casts/:id" => "home#index" 

  root "pages#home"

  get "about" => "pages#about"

  get "contact" => "pages#contact"

  

  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <%= link_to "Urban Modl", root_path, class: "navbar-brand" %>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Post job", new_cast_path %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%=link_to "Find models", pins_path %></li>
      <li><%=link_to "Find a job", casts_path %></li>
      <li><%=link_to "Post a job", new_cast_path %></li>
      <li><%= link_to "Join", new_user_registration_path %></li>
      <li><%= link_to "Log in", new_user_session_path %></li>
       <% end %>
    </ul>

        
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Modlr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
		
	<%= yield %>

</body>
</html>